import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const posts = api.post.getAll.useQuery(undefined, {
    refetchOnWindowFocus: false,
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div>
          {posts.data?.map((post) => {
            return (
              <div key={post.id}>
                <p>{post.id}</p>
                <h1>{post.title}</h1>
                <p>{post.text}</p>
                <p>{post.createdAt.toString()}</p>
                <p>{post.updatedAt.toString()}</p>
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
};

export default Home;
